### ISSUE TITLE
Different results for similar tests in .log file

### ISSUE THREAD

**Issue by tiimoS** [ylya/horndroid#1]
Hi, 
I have run Horndroid against a sample apk from droidbench and get some confusing results. I see some tests, that first declare NO LEAK and then in a following similar test with the prefix [REF] report that it is a POTENTIAL LEAK. What is the difference between those two test cases and why does it report a different result? 

3 Test if register 3 leaks at line 48 in method onClick(Landroid/view/View;)V of the class Lorg/cert/sendsms/Button1Listener; to the sink i(Ljava/lang/String;Ljava/lang/String;)I:**NO LEAK**

4 **[REF]** Test if register 3 leaks at line 48 in method onClick(Landroid/view/View;)V of the class Lorg/cert/sendsms/Button1Listener; to the sink i(Ljava/lang/String;Ljava/lang/String;)I:**POTENTIAL LEAK**

Furthermore, to what file is the line number referencing? In the src code there is no line 48 and in the decompiled .smali file (using apktool) line 48 is empty. 
Thanks for the support!

**Comment by ylya** [comment]
Hi Timo,

thank you for your interest in HD!
For every register HD performs two tests:

- first test checks the over-approximated label of the data in the register;
- second test checks the joined label of the heap data accessible by a reference stored in the register.

HD analyses bytecode of applications, so the line number is the program counter associated to the bytecode instruction.

Let me know if there any other questions!

Bests,
Ilya

**Comment by tiimoS** [comment]
Hi Ilya, 
Thanks for the quick feedback. I went over the HornDroid paper to get a better understanding of the proposed solution. However, I still don't fully understand the reported issues i.e. the difference between the two queries. Hopefully, you can further enlighten me :) 

I've used the SendSMS.apk from DroidBench for a short test. HD reported line 48 to be problematic (last line in code snippet below). This is in fact the source of the critical information (Device UID) which is later on leaked over sms and to the log files. 
```
public void onClick(android.view.View)
    {
        org.cert.sendsms.Button1Listener $r0;
        android.view.View $r1;
        android.content.Intent $r2;
        org.cert.sendsms.MainActivity $r3;
        java.lang.Object $r4;
        android.telephony.TelephonyManager $r5;
        java.lang.String $r6;
        java.lang.StringBuilder $r7;

        $r0 := @this: org.cert.sendsms.Button1Listener;

        $r1 := @parameter0: android.view.View;

        $r2 = new android.content.Intent;

        specialinvoke $r2.<android.content.Intent: void <init>(java.lang.String)>("android.intent.action.SEND");

        virtualinvoke $r2.<android.content.Intent: android.content.Intent setType(java.lang.String)>("text/plain");

        $r3 = $r0.<org.cert.sendsms.Button1Listener: org.cert.sendsms.MainActivity act>;

        $r4 = virtualinvoke $r3.<org.cert.sendsms.MainActivity: java.lang.Object getSystemService(java.lang.String)>("phone");

        $r5 = (android.telephony.TelephonyManager) $r4;

        $r6 = virtualinvoke $r5.<android.telephony.TelephonyManager: java.lang.String getDeviceId()>();
```
Now, HD performed four test queries for this method. First it tested register 3 (one time over-approx. label and one time with the addition [REF], so the joined label of the heap data). Secondly, it checked register 4 the same way. 
For register 3, only the [REF] query indicated a potential issues. Now, as can be seen above, register 3 only contains the MainActivity. This Activity contains the sendSMS method, where the uid is leaked. So it is unclear to me, why those two queries report different leak evaluations. 
The check for register 4 returned a positive leak for both queries. Nonetheless, if I understand the code above correctly r4 only contains the telephonyManager. How is this a potential leakage?

Thanks a lot for your support!
Best, 
Timo

**Comment by ylya** [comment]
Hi Timo,

Thank you for the question!

HD generates tests only for calls to the methods that are considered to be information sinks and, as you have mentioned, at 48 the call to the source is performed. Still HD reports that the problem occurs when calling method
`i(Ljava/lang/String;Ljava/lang/String;)I`
not `getDeviceId()>();`
Most likely,`i(Ljava/lang/String;Ljava/lang/String;)I` is the logging method which is executed later.

I guess there is a confusion between the line numbers in the smali file and the bytecode numbers: smali file line 48 is not bytecode line 48, this makes results interpretation rather complicated, but at least HD reports class, method and a particular call inside the method that causes the trouble. 

Later I will add the printing of the bytecode input with the line numbers to avoid the confusion.

Bests,
Ilya

**Comment by tiimoS** [comment]
Hi Ilya, 
Thanks for the quick reply. You are right, the sink is with method i(...). However, I really don't get why I get reported two different leak indications for register 3. 

Printing the bytecode is a great idea and will definitely enhance the usability 👍
