### ISSUE TITLE
[OT] - Ethertrust source code

### ISSUE THREAD

**Issue by herrBez** [ylya/horndroid#2]
Hi,

I am wondering if it is planned to make the ethertrust code available on GitHub or an equivalent platform (I found the source code on netidee.at), but it would be better to make the ethertrust code available so that one can add PR or issue to improve the tool.

--
Cheers from Italy,
Mirko

**Comment by ylya** [comment]
Hi Mirko,

EtherTrust code will be definitely available on GitHub, cannot tell when exactly, I hope in the coming months.
I am really happy to see your interest!

Bests,
Ilya

**Comment by ylya** [comment]
Hi Mirko,

the sources of what EtherTrust project has become are available here:

https://secpriv.wien/ethor/

Bests,
Ilya
