### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by ambiso** [ylya/horndroid#3]
Hi!

unfortunately the website that is linked in the project description is no longer available: https://secpriv.tuwien.ac.at/tools/horndroid .

Additionally the links to the papers in the README don't function anymore.

**Comment by ylya** [comment]
Hello,

The website's migration caused the issues.
Now they should be all up.

Thank you for reporting those!

Bests,
Ilya

**Comment by ambiso** [comment]
Unfortunately the links in the readme remain non-functioning

**Comment by ylya** [comment]
Yes, you are right, sorry.

They should be working now.

Thank you!

Bests,
Ilya

**Comment by ambiso** [comment]
Thanks!
